### ISSUE TITLE
Closing Programs started with shortcuts

### ISSUE THREAD

**Issue by BCNelson** [antivanov/Brackets-Command-Line-Shortcuts#12]
There dose not seem to be a way to close long running programs. I would expect the to close when I close the Feedback Panel or be able to use CTRL+C to kill the currently running process. now i have to start Task manager find the cmd.exe and "kill process tree"

FYI: I'm using it to start the Django Dev Server.

**Comment by amoilanen** [comment]
Thanks for reporting the issue, I will take a look soon
