### ISSUE TITLE
Nothing happens when I press the key combination

### ISSUE THREAD

**Issue by etlweather** [antivanov/Brackets-Command-Line-Shortcuts#7]
I created a configuration like so:
```
[
  {
    "name": "Check Puppet File",
    "dir": "$PROJECT_ROOT",
    "cmd": "puppet parser validate $SELECTED_ITEM",
    "shortcut": "Ctrl-Alt-X",
    "autohide": false
  },
]
```
When I press the key combination (and I tried several different combinations), nothing happens. I checked the error console and nothing there either.

Not sure what else to check for.

**Comment by antivanov** [comment]
Are there any errors in the logs or in the Developer Tools (F12)? Which version of Brackets do you use?

**Comment by etlweather** [comment]
I am using Brackets version 1.1.0-15558. Only errors in the Console are from some themes.

**Comment by etlweather** [comment]
I just reloaded once again and I saw an error this time: `Unexpected token ]` - checking...

**Comment by etlweather** [comment]
Sorry about that - somehow I did not see that error earlier. I have been writing too much Puppet code lately - you end anything and everything with a comma but obviously in standard JSON you don't. My bad - thanks for this extension, it's awesomely useful.

**Comment by antivanov** [comment]
Good, thanks. Please, report any issues you find. 

Maybe I should improve error handling for the extension so that it will be more obvious that the error is in the configuration.
