### ISSUE TITLE
Suggestion: Make dir optional

### ISSUE THREAD

**Issue by CupOfTea696** [antivanov/Brackets-Command-Line-Shortcuts#9]
Since most of the time you'd want to run commands from the project root (e.g. for most git actions), wouldn't it be easier to default the `dir` setting to `$PROJECT_ROOT`?

**Comment by antivanov** [comment]
Looks reasonable, thank you, I will implement this change soon.

**Comment by CupOfTea696** [comment]
Great :D

**Comment by antivanov** [comment]
Implemented the requested behavior, released in the plugin version 0.2.4

Please, re-open the issue if the solution does not work for you.

**Comment by CupOfTea696** [comment]
That was fast!
